version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
      - ./:/var/www/app
    networks:
      - app
  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/var/www/app
      - ./conf/php-fpm:/etc/php-fpm.d
    network_mode: service:nginx
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./storage:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    networks:
      - app
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "8000:8080"
    depends_on:
      - mysql
    networks:
      - app
networks:
  app:
    driver: bridge